version: '3.9'
services:
    mysql_registroPersonas:
        image: mysql/mysql-server:latest
        ports:
            - "5000:3306"
        restart: always
        volumes:
            - db_volume_registroPersonas:/var/lib/mysql
            - ./Database/PersonasDatabase.sql:/docker-entrypoint-initdb.d/PersonasDatabase.sql:ro
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_0900_ai_ci']
        environment: 
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_HOST: localhost
            MYSQL_DATABASE: "PersonasDatabase"
            MYSQL_USER: "root"
        container_name: db_Personas

    simple_app:
        image: personasregistro
        depends_on: 
           - "mysql_registroPersonas"
        build: 
           context: ./Programa/
           dockerfile: Dockerfile
        stdin_open: true
        tty: true
        environment: 
           DB_CONNECTION_STRING: "server=mysql_registroPersonas;user=PersonaAdmin;password=bobcholo1;database=PersonasDatabase"
        container_name: app_Personas

volumes:
    db_volume_registroPersonas: